Jane camera button
aau-giraf/weekplan pull request #141
Opened 2024-11-01 16:28 UTC by Jane2353

Added a button and openCamera function to take photos. Unit tests also made to ensure the camera works correctly.

- Bugfix
- Feature
- Code style update
- Refactor
- Documentation update
- Other (please describe):

## Checklist

- [x] Code follows the code guidelines
- [x] Tests have been added/updated (if applicable)

2024-11-01 23:59 UTC, MaksimHamko submitted a review, later dismissed
Everything looks good, maybe a bit too much comments ;)

2024-11-02 08:23 UTC, MertzAndreas requested changes
Code looks good, I agree with Maksim that the amount of comments are bit overwhelming. 🕺

2024-11-02 08:23 UTC, MertzAndreas commented on components/Camera/Camera.tsx
> +export const openCamera = async () => {
Question does this function open the camera only? It seems to me that it opens the camera and allows for a picture to be taken. If that's the case I would prefer a different name.

2024-11-04 13:41 UTC, MertzAndreas approved these changes
Smukt ;)

2024-11-04 13:43 UTC, Tbjerregaard approved these changes

2024-11-04 13:44 UTC, merged