Profile page logic
aau-giraf/weekplan pull request #145
Opened 2024-11-03 19:43 UTC by MertzAndreas

## Description

Added UI changes such as icon button animations, also partially implemented hook and API interaction for organisation interactions. Create Org works but rest is implemented in a different page.

## Type of PR

- Feature
- Refactor

## Related Issues/Tickets

#132 (Partial as @MaksimHamko creates the view for invitations)

## Checklist

- [] Completed the user story described by the issue (if applicable)
- [X] Code follows the code guidelines
- [X] Tests have been added/updated (if applicable)

2024-11-04 08:15 UTC, Tbjerregaard requested changes
Overall good only found one small typo. One change that could be nice would be when the user is creating an organisation that they would be able to cancel it a bit more intuitively/easier . The action of swiping it back down is not very user friendly imo, at least I experienced a skill issue for a bit.

2024-11-04 08:15 UTC, Tbjerregaard commented on apis/organisationAPI.ts
> +  if (!res.ok) throw new Error("Kunne ikke slette organisation");
"Kunne ikke oprette organisation"*

2024-11-04 13:28 UTC, DanielRBech submitted a review, later dismissed
I like - well done 💯

2024-11-04 21:04 UTC, Tbjerregaard commented on __tests__/useOrganisation.test.tsx
> +
this is nice

2024-11-05 08:33 UTC, Simo205j approved these changes

2024-11-05 08:34 UTC, merged