Create invitations
aau-giraf/weekplan pull request #187
Opened 2024-11-07 23:45 UTC by MaksimHamko

## Description

You can invite people to organisations using their email

## Type of PR

- Feature

## Related Issues/Tickets
https://github.com/aau-giraf/weekplan/issues/82

## Checklist

- [x] Completed the user story described by the issue (if applicable)
- [x] Code follows the code guidelines
- [x] Tests have been added/updated (if applicable)
- [x] Documentation has been updated (if applicable)

2024-11-08 06:43 UTC, MertzAndreas requested changes
Please set up prettier and go through the files 😮‍💨

2024-11-08 06:43 UTC, MertzAndreas commented on apis/invitationAPI.ts
> +  console.log(newInvitation);
eww

2024-11-08 06:43 UTC, MertzAndreas commented on hooks/useInvitation.ts
> +    }
Either these functions should be deleted set the cache of the organisation which has invited this user.

2024-11-08 23:56 UTC, Azzi132 approved these changes
Looks good!

2024-11-09 11:03 UTC, MertzAndreas requested changes

2024-11-09 11:03 UTC, MertzAndreas commented on app/create-invitation.tsx
Migrate this to the new form API and components

2024-11-09 14:50 UTC, MertzAndreas approved these changes

2024-11-09 14:50 UTC, MertzAndreas commented on app/create-invitation.tsx
> +  const createInv = createInvitation;
What's this?

2024-11-09 14:52 UTC, MertzAndreas requested changes

2024-11-09 14:52 UTC, MertzAndreas commented on app/create-invitation.tsx
> +  const createInv = createInvitation;
Why not just use as it?

2024-11-09 17:12 UTC, MertzAndreas approved these changes

2024-11-09 17:13 UTC, merged