Moved change password forms to a new seperate screen
aau-giraf/weekplan pull request #205
Opened 2024-11-09 17:53 UTC by Azzi132

## Description

Moved the change password forms into an seperate screen that can be accessed from the editProfile screen. Also removed a console.log.

## Type of PR

- Refactor

## Related Issues/Tickets

Please link the related issues/tickets here.

## Checklist

- [✓] Completed the user story described by the issue (if applicable)
- [✓] Code follows the code guidelines
- [] Tests have been added/updated (if applicable)
- [] Documentation has been updated (if applicable)

2024-11-11 12:04 UTC, Tbjerregaard requested changes
Overall looks good, I just the one small request. (plus the fix of merge conflicts as the app _layout have changed).

2024-11-11 20:13 UTC, Azzi132 commented on app/changepassword.tsx
> +      />
Done!

2024-11-12 09:33 UTC, Tbjerregaard approved these changes

2024-11-12 09:34 UTC, Stoldt approved these changes
LGTM 👍

2024-11-12 09:35 UTC, merged