Profile picture
aau-giraf/weekplan pull request #226
Opened 2024-11-15 14:31 UTC by MertzAndreas

## Description

Register flow with upload image and multistep form. Also renamed some folders to comply with naming conventions 

## Type of PR

- Feature
- Code style update

## Related Issues/Tickets

#225 

## Checklist

- [X] Completed the user story described by the issue (if applicable)
- [X] Code follows the code guidelines
- [X] Tests have been added/updated (if applicable)
- [X] Documentation has been updated (if applicable)

2024-11-15 23:26 UTC, Tbjerregaard requested changes
overall sehr gut

2024-11-15 23:26 UTC, Tbjerregaard commented on apis/profileAPI.ts
> +  //TypeScript doesn't this format, so we need to typecast it
🤣

2024-11-15 23:28 UTC, Tbjerregaard requested changes

2024-11-15 23:28 UTC, Tbjerregaard commented on components/ProgressSteps.tsx
> +});
sharedStyles?

2024-11-16 00:57 UTC, Tbjerregaard approved these changes

2024-11-16 14:00 UTC, MaksimHamko approved these changes
Good code styling

2024-11-16 14:01 UTC, merged