Design fixing v3
aau-giraf/weekplan pull request #275
Opened 2024-11-27 14:29 UTC by MaksimHamko

## Description

Cs fixing and changes to components so it all looks better 

## Type of PR

- Feature
- Code style update

## Checklist

- [] Completed the user story described by the issue (if applicable)
- [x] Code follows the code guidelines
- [] Tests have been added/updated (if applicable)
- [] Documentation has been updated (if applicable)

2024-11-27 14:32 UTC, DanielRBech requested changes

2024-11-27 14:32 UTC, DanielRBech commented on app/auth/profile/organisation/addactivity.tsx
> +          <View style={{ flexGrow: 1 }}>
Not centered

2024-11-27 21:54 UTC, MertzAndreas requested changes
Vi tager dem i morgen 😘💩

2024-11-28 08:07 UTC, MertzAndreas approved these changes

2024-11-28 08:20 UTC, DanielRBech approved these changes
![giphy](https://github.com/user-attachments/assets/4892eeea-5d9b-4c83-9a3a-5d8b98edbdfa)

2024-11-28 08:31 UTC, merged