Week overview
aau-giraf/weekplan pull request #73
Opened 2024-10-17 06:44 UTC by MertzAndreas

## Description

This is our increment for sprint 1, it includes most features for the week overview page, except for error handling and pictograms which is dependent on functionality which is yet to be implemented on the backend. 

## Type of PR

- Increment 

## Related Issues/Tickets

#53 #71 #72

## Checklist

- [X] Code follows the code guidelines
- [X] Tests have been added/updated (if applicable)
- [] Documentation has been updated (if applicable)

2024-10-17 13:59 UTC, LokeSGJ requested changes
Ser rigtig godt ud, har nogle småting med kommentarer og funktionsnavne men ellers er den approved 👍

2024-10-17 13:59 UTC, LokeSGJ commented on hooks/useActivity.ts
> + * and caching to provide a good user experience.
Der er et par typos her, tænker der skulle stå "recommended" og "optimistic"

2024-10-17 13:59 UTC, LokeSGJ commented on hooks/useSwipeGesture.ts
> +      //WE NEED THIS TO RUN ON THE UI THREAD
Er det her en TODO? Vær opmærksom på at få den slettet når den bliver fixet, kan være forvirrende at finde en deprecated kommentar i en stor kodebase

2024-10-17 13:59 UTC, LokeSGJ commented on apis/activityAPI.ts
> +export const fetchRequest = async (id: number, date: Date) => {
Måske skulle denne her have et andet navn der differentierer den bedre fra fetchActivityRequest. Kunne fx. være fetchByDateRequest og fetchByIdRequest. I kunne også beholde navnene men bare lige skrive kommentarer om hvad de gør

2024-10-17 14:34 UTC, LokeSGJ approved these changes
Ser godt ud 👍

2024-10-17 14:49 UTC, LokeSGJ approved these changes

2024-10-18 08:37 UTC, Azzi132 commented
Looks good! 👍

2024-10-18 08:42 UTC, Azzi132 approved these changes
Looks good! 👍

2024-10-18 08:44 UTC, merged